services:
  # Backend API
  - type: web
    name: afilliagroup-api
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install && npm run db:generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false # O usu√°rio vai colar o link do banco dele no painel do Render
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        fromService:
          type: static
          name: afilliagroup-panel
          property: url

  # Frontend Static Site
  - type: static
    name: afilliagroup-panel
    plan: free
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: afilliagroup-api
          property: url
